version: '2.1'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "A2P_BotsGW-swagger-editor"
    ports:
      - "8001:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "A2P_BotsGW-swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml